version: '3.8'

services:
  app:
    build: .
    ports:
      - "5602:5602"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SERVER_PORT=5602
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - memmory-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - memmory-network

volumes:
  qdrant_data:

networks:
  memmory-network:
    driver: bridge 